apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: poc-llm-bot
  labels:
    app: poc-llm-bot
spec:
  type: ClusterIP
  selector:
    app: poc-llm-bot
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000